fieldLayouts:
  f0593b17-30d2-4c02-9ce8-fb4f30170825:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b4702396-24b4-44a2-bddf-38125d98c0d0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d90131b1-fc22-454b-b5ae-e95cfa6373d3 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0b13959-1694-4499-934e-d5356db46e25
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 851826b7-2285-45c7-bae4-b6586316269f
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: efcba510-ae58-450c-a6b3-8b55c1fdb11a # Text
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
