fieldLayouts:
  ad393189-39b4-4556-9880-12d98f6543a7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 52d5fc41-4868-4255-a1e8-60a2b89c56e5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f24d7071-c1c8-436f-a818-f29cd02cc5d4 # Default Slot
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 425e56c2-4678-43b3-89a7-2097551e8ad2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ac5db6c9-1e7c-4160-b2d8-821018b66d09
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 23297f7e-0852-48f7-999f-929b36f11d78 # Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
