field: 13da94fd-499a-47fb-8b91-b0f580ccbad7 # Sample Matrix Field
fieldLayouts:
  f2780474-7369-405b-a54f-c3f948ee832f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 701952c9-d61c-4309-ae53-c8f47df309d8 # Some Text Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b3f2e4a-8b11-4f98-82e3-560ff190eb83
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2902fe2e-c453-4d27-9051-b3ba22b36362 # Another Lightswitch Field
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1cc3e946-7c12-46ae-bdcd-d10b8e557808
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d5f40e99-42a1-42eb-aea3-c26a4d545dc6
        userCondition: null
fields:
  2902fe2e-c453-4d27-9051-b3ba22b36362: # Another Lightswitch Field
    columnSuffix: zjvyzxwk
    contentColumnType: boolean
    fieldGroup: null
    handle: anotherLightswitchField
    instructions: null
    name: 'Another Lightswitch Field'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  701952c9-d61c-4309-ae53-c8f47df309d8: # Some Text Field
    columnSuffix: somrrhep
    contentColumnType: text
    fieldGroup: null
    handle: someTextField
    instructions: null
    name: 'Some Text Field'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: sampleBlock
name: 'Sample Block'
sortOrder: 1
