defaultPlacement: end
enableVersioning: true
handle: text
name: Text
propagationMethod: all
siteSettings:
  e0d545ea-1605-4ab3-9fcd-43050086f21b: # Igloo
    enabledByDefault: true
    hasUrls: true
    template: text/_entry
    uriFormat: 'text/{slug}'
type: channel
